import type { NextPage } from 'next';
import Head from 'next/head';
import Link from "next/link";
import Footer from '../components/Footer';
import Nav from '../components/Nav';

import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Web Magang</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className={styles.main}>
        <h1 className={styles.title}>
          WEB <span>MAGANG</span>
        </h1>

        <div className={styles.grid}>
          
          <div className={styles.card}>
            <Link href="/portofolio/port" >
              <h2>Portofolio &rarr;</h2>
            </Link>
            <p>Portofolio Surya Tirta Chandra</p>
          </div>

          <div className={styles.card}>
            <Link href="/video/dashboard">
              <h2>Video Gallery &rarr;</h2>
            </Link>
            <p>Project 1 Web Video Gallery</p>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  )
}

export default Home
